"""Session-safe, scheduler-backed interactive review support."""

from __future__ import annotations

import base64
import json
import mimetypes
import re
import secrets
import threading
import time
from collections.abc import Callable, Generator
from contextlib import contextmanager
from dataclasses import dataclass, field
from enum import StrEnum
from html.parser import HTMLParser
from pathlib import Path
from typing import Literal, Protocol, cast
from urllib.parse import unquote, urlsplit

from anki import scheduler_pb2
from anki.cards import Card, CardId
from anki.decks import DeckId
from anki.errors import NotFoundError
from anki.sound import AVTag, TTSTag
from fastmcp.tools import ToolResult
from mcp.types import AudioContent, ContentBlock, ImageContent, TextContent
from pydantic import BaseModel, ConfigDict, Field

from anki_connect_server.anki_wrapper import AnkiWrapper

type ReviewSide = Literal["question", "answer"]
type QueueKind = Literal["new", "learning", "review"]
type MediaKind = Literal[
    "image",
    "audio",
    "video",
    "tts",
    "remote",
    "missing",
    "unsupported",
    "oversized",
]
type MediaExpectation = Literal["image", "audio", "video", "auto"]
type CardFingerprint = tuple[int, ...]

REVIEW_TTL_SECONDS = 60 * 60
MAX_MEDIA_ITEM_BYTES = 5 * 1024 * 1024
MAX_MEDIA_TOTAL_BYTES = 10 * 1024 * 1024

_AV_REFERENCE = re.compile(r"\[anki:play:([qa]):(\d+)]")
_SPACE = re.compile(r"[ \t\f\v]+")
_NEWLINES = re.compile(r"\n{3,}")
_BLOCK_TAGS = frozenset(
    [
        "address",
        "article",
        "aside",
        "blockquote",
        "div",
        "dl",
        "fieldset",
        "figcaption",
        "figure",
        "footer",
        "form",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "header",
        "hr",
        "li",
        "main",
        "nav",
        "ol",
        "p",
        "pre",
        "section",
        "table",
        "tr",
        "ul",
    ]
)
_MIME_OVERRIDES = {
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".mp3": "audio/mpeg",
    ".oga": "audio/ogg",
    ".ogg": "audio/ogg",
    ".svg": "image/svg+xml",
    ".wav": "audio/wav",
}


class ReviewRating(StrEnum):
    AGAIN = "again"
    HARD = "hard"
    GOOD = "good"
    EASY = "easy"


class _StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class QueueCounts(_StrictModel):
    deck: str
    new: int = Field(ge=0)
    learning: int = Field(ge=0)
    review: int = Field(ge=0)
    total: int = Field(ge=0)


class MediaManifestEntry(_StrictModel):
    media_id: str
    kind: MediaKind
    sides: list[ReviewSide]
    source: str
    filename: str | None = None
    mime_type: str | None = None
    content_index: int | None = Field(default=None, ge=1)
    omitted_reason: str | None = None


class ReviewCardPayload(_StrictModel):
    has_card: bool
    review_id: str | None = None
    card_id: int | None = None
    note_id: int | None = None
    deck: str
    model: str | None = None
    queue_kind: QueueKind | None = None
    question: str | None = None
    answer: str | None = None
    queue: QueueCounts
    media: list[MediaManifestEntry] = Field(default_factory=lambda: list[MediaManifestEntry]())
    message: str | None = None


class SubmitReviewResult(_StrictModel):
    review_id: str
    rating: ReviewRating
    card_id: int
    queue: QueueCounts


class _Scheduler(Protocol):
    def get_queued_cards(
        self, *, fetch_limit: int = 1, intraday_learning_only: bool = False
    ) -> scheduler_pb2.QueuedCards: ...

    def build_answer(
        self,
        *,
        card: Card,
        states: scheduler_pb2.SchedulingStates,
        rating: scheduler_pb2.CardAnswer.Rating.V,
    ) -> scheduler_pb2.CardAnswer: ...

    def answer_card(self, input: scheduler_pb2.CardAnswer) -> object: ...


class _MediaCollector:
    def __init__(self, wrapper: AnkiWrapper) -> None:
        self.wrapper = wrapper
        self.entries: dict[str, MediaManifestEntry] = {}
        self.blocks: list[ContentBlock] = []
        self.total_bytes = 0

    def add_av(self, tag: AVTag, side: ReviewSide) -> str:
        if not isinstance(tag, TTSTag):
            return self.add(tag.filename, side, "auto")
        source = f"tts:{tag.lang}:{tag.field_text}"
        entry = self._entry(f"tts:{source}", "tts", side, source)
        entry.omitted_reason = "TTS audio is generated by Anki and is not stored locally"
        return f"[TTS: {tag.field_text}]"

    def add(self, source: str, side: ReviewSide, expected: MediaExpectation) -> str:
        parsed = urlsplit(source)
        if parsed.scheme in ("http", "https") or parsed.netloc or source.startswith("//"):
            return self._describe(
                f"remote:{source}", "remote", side, source, "Remote media is not fetched"
            )
        if parsed.scheme:
            return self._describe(
                f"unsupported:{source}",
                "unsupported",
                side,
                source,
                f"Unsupported media URL scheme: {parsed.scheme}",
            )

        filename = unquote(parsed.path)
        key = f"local:{filename}"
        existing = self.entries.get(key)
        if existing is not None:
            self._add_side(existing, side)
            return self._marker(existing)

        mime_type = _MIME_OVERRIDES.get(Path(filename).suffix.lower())
        mime_type = mime_type or mimetypes.guess_type(filename)[0]
        kind = self._kind(mime_type, expected)
        entry = self._entry(key, kind, side, source, filename, mime_type)
        if kind == "video":
            return self._omit(entry, "video", "Video is described but not embedded in MCP output")
        if kind == "unsupported":
            return self._omit(entry, "unsupported", "Unsupported media type")

        try:
            path = self.wrapper.media_path(filename)
            size = path.stat().st_size
            if size > MAX_MEDIA_ITEM_BYTES:
                return self._omit(entry, "oversized", "Media file exceeds the 5 MiB per-item limit")
            if self.total_bytes + size > MAX_MEDIA_TOTAL_BYTES:
                return self._omit(
                    entry, "oversized", "Media file exceeds the 10 MiB per-card limit"
                )
            data = path.read_bytes()
        except ValueError as exc:
            return self._omit(entry, "unsupported", str(exc))
        except FileNotFoundError:
            return self._omit(entry, "missing", "Media file is missing from the collection")

        encoded = base64.b64encode(data).decode("ascii")
        content_index = len(self.blocks) + 1
        content_type = mime_type or "application/octet-stream"
        block: ContentBlock
        if kind == "image":
            block = ImageContent(type="image", data=encoded, mimeType=content_type)
        else:
            block = AudioContent(type="audio", data=encoded, mimeType=content_type)
        self.blocks.append(block)
        self.total_bytes += len(data)
        entry.content_index = content_index
        return self._marker(entry)

    def _describe(
        self,
        key: str,
        kind: MediaKind,
        side: ReviewSide,
        source: str,
        reason: str,
    ) -> str:
        return self._omit(self._entry(key, kind, side, source), kind, reason)

    def _entry(
        self,
        key: str,
        kind: MediaKind,
        side: ReviewSide,
        source: str,
        filename: str | None = None,
        mime_type: str | None = None,
    ) -> MediaManifestEntry:
        entry = self.entries.get(key)
        if entry is None:
            entry = MediaManifestEntry(
                media_id=f"media-{len(self.entries) + 1}",
                kind=kind,
                sides=[side],
                source=source,
                filename=filename,
                mime_type=mime_type,
            )
            self.entries[key] = entry
        else:
            self._add_side(entry, side)
        return entry

    @staticmethod
    def _kind(mime_type: str | None, expected: MediaExpectation) -> MediaKind:
        family = mime_type.split("/", 1)[0] if mime_type else ""
        if expected == "video" or family == "video":
            return "video"
        if expected in ("image", "audio") and family != expected:
            return "unsupported"
        return cast(
            MediaKind,
            family if family in ("image", "audio", "video") else "unsupported",
        )

    @staticmethod
    def _omit(entry: MediaManifestEntry, kind: MediaKind, reason: str) -> str:
        entry.kind = kind
        entry.omitted_reason = reason
        return _MediaCollector._marker(entry)

    @staticmethod
    def _add_side(entry: MediaManifestEntry, side: ReviewSide) -> None:
        if side not in entry.sides:
            entry.sides.append(side)

    @staticmethod
    def _marker(entry: MediaManifestEntry) -> str:
        return f"[{entry.kind}: {entry.filename or entry.source}]"


class _TextRenderer(HTMLParser):
    def __init__(
        self,
        collector: _MediaCollector,
        side: ReviewSide,
        question_av: list[AVTag],
        answer_av: list[AVTag],
    ) -> None:
        super().__init__(convert_charrefs=True)
        self.collector = collector
        self.side: ReviewSide = side
        self.av = {"q": question_av, "a": answer_av}
        self.parts: list[str] = []
        self.ignored = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = dict(attrs)
        if tag == "style" or (
            tag == "script" and not (attributes.get("type") or "").startswith("math/")
        ):
            self.ignored += 1
            return
        if self.ignored:
            return
        if tag == "br" or tag in _BLOCK_TAGS:
            self.parts.append("\n")
        source = attributes.get("src")
        if not source or tag not in ("img", "audio", "video", "source"):
            return
        expected = cast(MediaExpectation, {"img": "image"}.get(tag, tag))
        if tag == "source":
            family = (attributes.get("type") or "").partition("/")[0]
            expected = cast(MediaExpectation, family if family in ("audio", "video") else "auto")
        self.parts.append(self.collector.add(source, self.side, expected))

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)

    def handle_endtag(self, tag: str) -> None:
        if self.ignored:
            if tag in ("style", "script"):
                self.ignored -= 1
            return
        if tag in _BLOCK_TAGS:
            self.parts.append("\n")

    def handle_data(self, data: str) -> None:
        if self.ignored:
            return
        position = 0
        for match in _AV_REFERENCE.finditer(data):
            self.parts.append(data[position : match.start()])
            tags = self.av[match.group(1)]
            index = int(match.group(2))
            marker = (
                self.collector.add_av(tags[index], self.side)
                if index < len(tags)
                else "[unsupported: invalid Anki media reference]"
            )
            self.parts.append(marker)
            position = match.end()
        self.parts.append(data[position:])

    def text(self) -> str:
        text = "".join(self.parts).replace("\r\n", "\n").replace("\r", "\n")
        lines = (_SPACE.sub(" ", line).strip() for line in text.splitlines())
        return _NEWLINES.sub("\n\n", "\n".join(lines)).strip()


@dataclass
class _Review:
    review_id: str
    session_id: str
    deck: str
    card: Card
    states: scheduler_pb2.SchedulingStates
    generation: int
    fingerprint: CardFingerprint
    created_at: float
    payload: ReviewCardPayload
    blocks: list[ContentBlock]
    rating: ReviewRating | None = None
    result: SubmitReviewResult | None = None


@dataclass
class ReviewManager:
    wrapper: AnkiWrapper
    ttl_seconds: float = REVIEW_TTL_SECONDS
    clock: Callable[[], float] = time.monotonic
    reviews: dict[str, _Review] = field(default_factory=lambda: dict[str, _Review]())
    pending: dict[tuple[str, str], str] = field(
        default_factory=lambda: dict[tuple[str, str], str]()
    )
    lock: threading.RLock = field(default_factory=threading.RLock)

    def get_queue(self, deck: str) -> QueueCounts:
        with self.lock:
            return self._queue(deck)

    def get_next_card(self, session_id: str, deck: str) -> ToolResult:
        with self.lock:
            self._purge()
            deck_id, deck_name = self._deck(deck)
            key = (session_id, deck_name)
            if review_id := self.pending.get(key):
                review = self.reviews[review_id]
                return self._result(review.payload, review.blocks)

            with self._selected(deck_id):
                queued = self._scheduler().get_queued_cards(fetch_limit=1)
            counts = self._counts(deck_name, queued)
            if not queued.cards:
                payload = ReviewCardPayload(
                    has_card=False,
                    deck=deck_name,
                    queue=counts,
                    message="No cards are currently available in this deck's Anki review queue.",
                )
                return self._result(payload, [])

            queued_card = queued.cards[0]
            card = self.wrapper.col.get_card(CardId(queued_card.card.id))
            card.start_timer()
            rendered = card.render_output(reload=True)
            media = _MediaCollector(self.wrapper)
            question = self._render(
                rendered.question_text,
                "question",
                rendered.question_av_tags,
                rendered.answer_av_tags,
                media,
            )
            answer = self._render(
                rendered.answer_text,
                "answer",
                rendered.question_av_tags,
                rendered.answer_av_tags,
                media,
            )
            note = card.note()
            notetype = note.note_type()
            if notetype is None:
                raise ValueError(f"Card {card.id} has no note type")
            review_id = secrets.token_urlsafe(24)
            payload = ReviewCardPayload(
                has_card=True,
                review_id=review_id,
                card_id=int(card.id),
                note_id=int(note.id),
                deck=self.wrapper.col.decks.name(card.did),
                model=str(notetype["name"]),
                queue_kind=self._queue_kind(queued_card.queue),
                question=question,
                answer=answer,
                queue=counts,
                media=list(media.entries.values()),
            )
            review = _Review(
                review_id=review_id,
                session_id=session_id,
                deck=deck_name,
                card=card,
                states=queued_card.states,
                generation=self.wrapper.collection_generation,
                fingerprint=self._fingerprint(card),
                created_at=self.clock(),
                payload=payload,
                blocks=media.blocks,
            )
            self.reviews[review_id] = review
            self.pending[key] = review_id
            return self._result(payload, review.blocks)

    def submit(self, session_id: str, review_id: str, rating: ReviewRating) -> SubmitReviewResult:
        with self.lock:
            review = self.reviews.get(review_id)
            if review is None:
                self._purge()
                raise ValueError("Review ID is unknown or expired")
            if self.clock() - review.created_at >= self.ttl_seconds:
                self._drop(review)
                raise ValueError("Review ID is expired")
            if review.session_id != session_id:
                raise ValueError("Review ID belongs to a different MCP session")
            if review.result is not None:
                if review.rating != rating:
                    raise ValueError("Review ID was already submitted with a different rating")
                return review.result
            if review.generation != self.wrapper.collection_generation:
                self._drop(review)
                raise ValueError("Review ID is stale because the collection was reopened")
            try:
                current = self.wrapper.col.get_card(CardId(review.card.id))
            except NotFoundError as exc:
                self._drop(review)
                raise ValueError("Review ID is stale because the card no longer exists") from exc
            if self._fingerprint(current) != review.fingerprint:
                self._drop(review)
                raise ValueError("Review ID is stale because the card changed")

            scheduler = self._scheduler()
            answer = scheduler.build_answer(
                card=review.card,
                states=review.states,
                rating=self._rating(rating),
            )
            scheduler.answer_card(answer)
            result = SubmitReviewResult(
                review_id=review_id,
                rating=rating,
                card_id=int(review.card.id),
                queue=self._queue(review.deck),
            )
            review.rating = rating
            review.result = result
            review.blocks.clear()
            self.pending.pop((session_id, review.deck), None)
            return result

    def _queue(self, deck: str) -> QueueCounts:
        deck_id, name = self._deck(deck)
        with self._selected(deck_id):
            return self._counts(name, self._scheduler().get_queued_cards(fetch_limit=1))

    def _deck(self, deck: str) -> tuple[DeckId, str]:
        if not deck:
            raise ValueError("Deck name is required")
        deck_id = self.wrapper.col.decks.id_for_name(deck)
        if deck_id is None:
            raise ValueError(f"Unknown deck: {deck}")
        return deck_id, self.wrapper.col.decks.name(deck_id)

    @contextmanager
    def _selected(self, deck_id: DeckId) -> Generator[None]:
        previous = self.wrapper.col.decks.get_current_id()
        self.wrapper.col.decks.select(deck_id)
        try:
            yield
        finally:
            self.wrapper.col.decks.select(previous)

    @staticmethod
    def _counts(deck: str, queued: scheduler_pb2.QueuedCards) -> QueueCounts:
        return QueueCounts(
            deck=deck,
            new=queued.new_count,
            learning=queued.learning_count,
            review=queued.review_count,
            total=queued.new_count + queued.learning_count + queued.review_count,
        )

    @staticmethod
    def _queue_kind(queue: scheduler_pb2.QueuedCards.Queue.V) -> QueueKind:
        try:
            name = scheduler_pb2.QueuedCards.Queue.Name(queue).lower()
            if name not in ("new", "learning", "review"):
                raise ValueError
            return name
        except ValueError as exc:
            raise ValueError(f"Unknown Anki queue kind: {queue}") from exc

    @staticmethod
    def _render(
        html: str,
        side: ReviewSide,
        question_av: list[AVTag],
        answer_av: list[AVTag],
        media: _MediaCollector,
    ) -> str:
        renderer = _TextRenderer(media, side, question_av, answer_av)
        renderer.feed(html)
        renderer.close()
        return renderer.text()

    @staticmethod
    def _fingerprint(card: Card) -> CardFingerprint:
        return tuple(
            int(value)
            for value in (
                card.id,
                card.nid,
                card.did,
                card.ord,
                card.type,
                card.queue,
                card.due,
                card.ivl,
                card.factor,
                card.reps,
                card.lapses,
                card.left,
                card.mod,
                card.usn,
            )
        )

    @staticmethod
    def _rating(rating: ReviewRating) -> scheduler_pb2.CardAnswer.Rating.V:
        return scheduler_pb2.CardAnswer.Rating.Value(rating.upper())

    def _scheduler(self) -> _Scheduler:
        return cast(_Scheduler, self.wrapper.col.sched)

    def _purge(self) -> None:
        for review in list(self.reviews.values()):
            if self.clock() - review.created_at >= self.ttl_seconds:
                self._drop(review)

    def _drop(self, review: _Review) -> None:
        self.reviews.pop(review.review_id, None)
        if review.result is None:
            self.pending.pop((review.session_id, review.deck), None)

    @staticmethod
    def _result(payload: ReviewCardPayload, blocks: list[ContentBlock]) -> ToolResult:
        structured = payload.model_dump(mode="json")
        return ToolResult(
            content=[
                TextContent(
                    type="text",
                    text=json.dumps(structured, ensure_ascii=False, separators=(",", ":")),
                ),
                *blocks,
            ],
            structured_content=structured,
        )
